# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Шайдуллин Руслан Дамирович
- ЗПИЭ-21-1

| Задание | Сам_раб |
| ------  | ------ |
| Задание 1 | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы.

```python
import time

def timer_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f'\nФункция была выполнена за {end_time - start_time:.4f} сек.')
        return result
    return wrapper

@timer_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат.
![Меню](https://github.com/stratch1989/ProgramEngineering/blob/Theme_10/img/task1.png)

## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(filename):
    try:
        file = open(filename, 'r', encoding='utf-8-sig')
        content = file.read()
        if not content:
            raise Exception("Файл пустой")
        print(content)
    except Exception as e:
        print(str(e))


if __name__ == '__main__':
    read_file('empty.txt')
    read_file('noempty.txt')
```

### Результат.
![Меню](https://github.com/stratch1989/ProgramEngineering/blob/Theme_10/img/task2.png)

## Самостоятельная работа №3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль.

```python
def sum_two_numbers():
    try:
        num = float(input('Введите число:\n'))
        res = num + 2
        return res
    except ValueError:
        return 'Неподходящий тип данных. Ожидалось число.'

print(sum_two_numbers())
```

### Результат.
![Меню](https://github.com/stratch1989/ProgramEngineering/blob/Theme_10/img/task3.png)

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class MyCustomException(Exception):
    pass

try:
    raise MyCustomException("Пример ошибки")
except MyCustomException as e:
    print("Обработка ошибки:", e)

def divide_numbers(a, b):
    if b == 0:
        raise MyCustomException("Деление на ноль")
    return a / b

try:
    result = divide_numbers(10, 0)
    print("Результат деления:", result)
except MyCustomException as e:
    print("Обработка ошибки:", e)
```

### Результат.
![Меню](https://github.com/stratch1989/ProgramEngineering/blob/Theme_10/img/task4.png)

## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
class MyCustomException(Exception):
    pass

def check_positive_number(number):
    if number < 0:
        raise MyCustomException("Отрицательные числа не допускаются")

try:
    check_positive_number(-5)
except MyCustomException as e:
    print("Ошибка:", e)

def process_data(data):
    if not data:
        raise MyCustomException("Пустые данные обнаружены")

try:
    process_data([])
except MyCustomException as e:
    print("Ошибка:", e)
```

### Результат.
![Меню](https://github.com/stratch1989/ProgramEngineering/blob/Theme_10/img/task5.png)